plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.subhasish.gfbot'
    compileSdk 33

    defaultConfig {
        applicationId "com.subhasish.gfbot"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        compose true
    }

    composeOptions {
        // Matches Kotlin 1.8.10
        kotlinCompilerExtensionVersion '1.4.3'
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'androidx.activity:activity-compose:1.7.0'
    
    // Stable BOM version
    implementation platform('androidx.compose:compose-bom:2023.03.00')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui-tooling-preview'
}
